config/routes.rb
Rails.application.routes.draw do
 
 
  get 'static_pages/sandbox'

  root 'static_pages#intro'

  get '/game', to: 'static_pages#game'

  get '/repeated', to: 'static_pages#repeated'

  get '/representation', to: 'static_pages#representation'

  get '/representation2', to: 'static_pages#representation2'

  get '/cycle', to: 'static_pages#cycle'

  get '/payoff', to: 'static_pages#payoff'

  get '/run', to: 'static_pages#run'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def sandbox
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

   <a href ="https://gitlab.com/ayaderaghul/thesis"> Gitlab Project </a> | Made with <span style="color:#f4656d">&#9829;</span> | <a href="https://github.com/ayaderaghul" style="color:#bb8f5b">Aya de Raghũl</a> | <%= link_to image_tag("mint.jpg", style:'width:2%') %>

   
	


</footer>

app/views/layouts/_nav.html.erb
 <nav>
	<ul>
	  <li> <%= link_to "0. Introduction", root_path %> </li>
	  <li> <%= link_to "I. The Game", game_path %> </li>
	  <li> <%= link_to "II. The Repeated Game", repeated_path %></li>
	  <li> <%= link_to "III. Strategy Representation", representation_path %></li>
	  <li> <%= link_to "III. Strategy Representation 2", representation2_path %></li>
	  <li> <%= link_to "IV. Simulation Cycle", cycle_path %></li>
	  <li> <%= link_to "V. Payoff Calculation", payoff_path %></li>
	  <li> <%= link_to "VI. Run", run_path %></li>
	  <div class="courtesy">
	    <%= link_to image_tag( yield(:image) ) %>
	    <p>courtesy:  <%= yield(:author) %> </p>
	  </div>
	</ul>
    </nav>

app/views/layouts/_ndg.html.erb
	    <p>
	    <strong> Exercise </strong> I give you the Nash Demand Game in which there is 10 euro to be divided between two players. Each player can claim 2, 5 or 8 out of 10 which is equivalent to a Low, Medium or High portion of the pie, if the prize is ever interpreted as a pie. If the two claims sum up to be less than or equal 10, each gets what they wants, otherwise both get zero.
</p>
	<table>
	    <tr>
		<th>P1 \ P2 </th>
		<th>Low</th>
		<th>Medium</th>
		<th> High  </th>
	    </tr>
	    <tr>
		<td>Low</td>
		<td>2 2</td>
		<td>2 5</td>
		<td class="ne"> 2 8 </td>
	    </tr>
	    <tr>
		<td>Medium</td>
		<td>5 2</td>
		<td class="ne">5 5</td>
		<td> 0 0 </td>
	    </tr>
	    <tr>
		<td> High </td>
		<td class="ne"> 8 2 </td>
		<td> 0 0 </td>
		<td> 0 0 </td>
	    </tr>
	</table> 

app/views/layouts/_pd.html.erb
 <svg>
   <rect x="5%" y="20" width="30%" height="80"/>
   <rect x="35%" y="20" width="30%" height="80"/>
   <rect x="65%" y="20" width="30%" height="80"/>
   
   <line x1="5%" y1="20" x2="35%" y2="100"/> 
   
   <rect x="5%" y="100" width="30%" height="80"/>
   <rect x="35%" y="100" width="30%" height="80"/>
   <rect x="65%" y="100" width="30%" height="80"/>
   
   <rect x="5%" y="180" width="30%" height="80"/>
   <rect x="35%" y="180" width="30%" height="80"/>
   <rect x="65%" y="180" width="30%" height="80"/>
   
   <text x="25%" y="50" fill="#f4656d">P2</text>
   <text x="10%" y="70" fill="#008eb3">P1</text>
   <text x="42%" y="50" fill="#f4656d">Cooperate</text>
   <text x="73%" y="50" fill="#f4656d">Defect</text>
   <text x="10%" y="150" fill="#008eb3">Cooperate</text>
   <text x="45%" y="150" fill="#008eb3">3</text>
   <text x="55%" y="150" fill="#f4656d">3</text>
   <text x="75%" y="150" fill="#008eb3">0</text>
   <text x="85%" y="150" fill="#f4656d">4</text>
   
   <text x="10%" y="230" fill="#008eb3">Defect</text>
   <text x="45%" y="230" fill="#008eb3">4</text>
   <text x="55%" y="230" fill="#f4656d">0</text>
   <text x="75%" y="230" fill="#008eb3">1</text>
   <text x="85%" y="230" fill="#f4656d">1</text>
 </svg>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evolutionary Game Theory Simulation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="content">
       
    <%= yield %>
        

    <%= render 'layouts/footer' %>

    </div>

<%= render 'layouts/nav' %>

  </body>
</html>

app/views/static_pages/cycle.html.erb
<% provide(:image, "north.jpg") %>
<% provide(:author, "r.omas") %>

<header>IV. Simulation Cycle </header>
	    <div>
	    <h1> Interactive section 0 </h1>
	    <p> Imagine a world with many slots. We are going to fill these slots with a population of agents. In this project I would use a population of a fixed size N = 100 agents. Agents do agency: give them a contract, they execute the contract until terminated. Which means that we would give them different strategies.</p>
	    <p><strong> Click 0 to reset. Click other numeric buttons to go through this section.</strong></p>
	    <p><span><button type="button" onclick="IVstep0()">0</button><button type="button" onclick="IVstep1()">1</button><button type="button" onclick="IVstep2()">2</button><button type="button" onclick="IVstep3()">3</button><button type="button" onclick="IVstep4()">4</button><button type="button" onclick="IVstep5()">5</button><button type="button" onclick="IVstep6()">6</button><button type="button" onclick="IVstep7()">7</button> </span></p>
	    <div class="caption" style="height: 180px"> >  <p class="cap0">In the begining, there is the population of agents.</p></div>
	    </div>
	    <svg width="100%" height="450">
		<rect width="400" height="400" style="fill:#e4dbbe;stroke-width:3;stroke:#008eb3" />
		<text class="phase" x="50" y="450" fill="black" opacity="0">MATCHING PHASE</text>

		<g class="path" fill="none" stroke="#bb8f5b" stroke-width="10" stroke-dasharray="7,7" opacity="0">
		    <path d="M 40 40 l60 30" />
		    <path d="M 90 190 l120 -40" />
		    <path d="M 150 350 l20 -120" />
		    <path d="M 260 300 l90 60" />
		    <path d="M 360 100 l-90 100" />
		</g>

		<circle cx="40" cy="40" r="20" fill="#bb8f5b" />
		<circle cx="120" cy="80" r="20" fill="#008eb3" />
		<circle cx="90" cy="190" r="20" fill="#f4656d" />	
		<circle cx="220" cy="150" r="20" fill="#f4656d" />
		<circle class="random" cx="150" cy="350" r="20" fill="#f4656d" />
		<circle cx="170" cy="230" r="20" fill="#f4656d" />
		<circle cx="260" cy="300" r="20" fill="#f4656d" />
		<circle class="switch" cx="340" cy="350" r="20" fill="#008eb3" />
		<circle cx="360" cy="100" r="20" fill="#a7e5e0" />
		<circle cx="270" cy="200" r="20" fill="#008eb3" />

		<path class="learn" d="M 200 400 q 20 -250 200 -100" stroke="#008eb3" stroke-dasharray="7,7" stroke-width="5" fill="none" opacity="0" />

		<g class="pay" fill="ghostwhite" opacity="0">
		    <text x="25" y="45" fill="ghostwhite">10</text>
		    <text x="110" y="85" fill="ghostwhite">23</text>			<text x="80" y="195" fill="ghostwhite">50</text>
		    <text x="210" y="155" fill="ghostwhite">50</text>
		    <text x="140" y="355" fill="ghostwhite">50</text>
		    <text x="160" y="235" fill="ghostwhite">50</text>
		    <text x="250" y="305" fill="ghostwhite">0</text>
		    <text x="330" y="355" fill="ghostwhite">0</text>
		    <text x="350" y="105" fill="ghostwhite">40</text>
		    <text x="260" y="205" fill="ghostwhite">15</text>
		</g>
		

		<g class="fitness" opacity="0">
		<circle cx="480" cy="20" r="20" fill="#bb8f5b" />
		<text x="470" y="25" fill="ghostwhite">10</text>
		<circle cx="480" cy="62" r="20" fill="#a7e5e0" />
		<text x="470" y="67" fill="ghostwhite">40</text>
		<circle cx="480" cy="104" r="20" fill="#f4656d" />	
		<text x="470" y="109" fill="ghostwhite">50</text>
		<circle cx="480" cy="146" r="20" fill="#f4656d" />
		<text x="470" y="151" fill="ghostwhite">50</text>
		<circle cx="480" cy="188" r="20" fill="#f4656d" />
		<text x="470" y="193" fill="ghostwhite">50</text>
		<circle cx="480" cy="230" r="20" fill="#f4656d" />
		<text x="470" y="235" fill="ghostwhite">50</text>
		<circle cx="480" cy="272" r="20" fill="#f4656d" />
		<text x="470" y="277" fill="ghostwhite">0</text>
		<circle cx="480" cy="314" r="20" fill="#008eb3" />
		<text x="470" y="319" fill="ghostwhite">0</text>
		<circle cx="480" cy="356" r="20" fill="#008eb3" />
		<text x="470" y="361" fill="ghostwhite">23</text>
		<circle cx="480" cy="398" r="20" fill="#008eb3" />
		<text x="470" y="403" fill="ghostwhite">15</text>
		
		<text x="380" y="450" fill="black">SUM = 288</text>
		</g>

		<g class="relative" opacity="0">
		    <rect x="550" y="0" width="60" height="15" style="fill:#bb8f5b;stroke:none" />

		    <rect x="550" y="15" width="60" height="60" style="fill:#a7e5e0;stroke:none" />
		    
		    <rect x="550" y="75" width="60" height="290" style="fill:#f4656d;stroke:none" />
		    <rect x="550" y="365" width="60" height="55" style="fill:#008eb3;stroke:none" />
		    <g class="fittext">

		    <text x="615" y="65" fill="#a7e5e0">40/288 = 14%</text>
		    <text x="615" y="200" fill="#f4656d">200/288 = 70%</text>
		    <text x="615" y="390" fill="#008eb3">38/288 = 12%</text>
		    <text x="615" y="25" fill="#bb8f5b">10/288 = 4%</text>
		    </g>
		    <text x="530" y="450" fill="black">Fitness vector</text>

		</g>
	    </svg>

app/views/static_pages/game.html.erb
<% provide(:image, "jane.jpg") %>
<% provide(:author, "t.hu") %>
	
<div>
  <header>I. The Game</header>
  <h1> Interactive section 0 </h1>
  <p><strong> Click 0 to reset. Click the numeric buttons to go through this section. </strong></p>
  <p><span> <button type="button" onclick="step0()">0</button><button type="button" onclick="step1()">1</button><button type="button" onclick="step2()">2</button><button type="button" onclick="step3()">3</button><button type="button" onclick="step4()">4</button><button type="button" onclick="step5()">5</button><button type="button" onclick="step6()">6</button><button type="button" onclick="step7()">7</button><button type="button" onclick="step8()">8</button> </span></p>
  <p> First of all, let's consider the payoff matrix of the most popular game: the Prisoner's Dilemma. </p>
  <div class="caption"> >  <p class="cap0"></p></div>
</div>	    	
<svg>
  <rect x="5%" y="20" width="30%" height="80"/>
  <rect x="35%" y="20" width="30%" height="80"/>
  <rect x="65%" y="20" width="30%" height="80"/>
  
  <line x1="5%" y1="20" x2="35%" y2="100"/> 
		
  <rect x="5%" y="100" width="30%" height="80"/>
  <rect x="35%" y="100" width="30%" height="80"/>
  <rect x="65%" y="100" width="30%" height="80"/>
  
  <rect x="5%" y="180" width="30%" height="80"/>
  <rect x="35%" y="180" width="30%" height="80"/>
  <rect x="65%" y="180" width="30%" height="80"/>
  
  <text x="25%" y="50" fill="#f4656d" opacity="1">P2</text>
  <text x="10%" y="70" fill="#008eb3" opacity="1">P1</text>
  <text class="reset0 p1payp2c0 p2strat0" x="42%" y="50" fill="#f4656d" opacity="1">Cooperate</text>
  <text class="reset0 p1payp2d0" x="73%" y="50" fill="#f4656d" opacity="1">Defect</text>
  
  <text class="reset0 p2payp1c0" x="10%" y="150" fill="#008eb3" opacity="1">Cooperate</text>
  <text class="reset0 p1payp2c0" x="45%" y="150" fill="#008eb3" opacity="1">3</text>
  <text class="reset0 p2pay0 p2payp1c0" x="55%" y="150" fill="#f4656d" opacity="1">3</text>
  <text class="reset0 p1payp2d0 p1pay0" x="75%" y="150" fill="#008eb3" opacity="1">0</text>
  <text class="reset0 p2pay0 p2payp1c0" x="85%" y="150" fill="#f4656d" opacity="1">4</text>
  <text class="star0 p2starp1c0" x="90%" y="150" fill="#f4656d" opacity="0">*</text>
  <text class="reset0 p2payp1d0" x="10%" y="230" fill="#008eb3" opacity="1">Defect</text>
  <text class="star0 p1starp2c0" x="40%" y="230" fill="#008eb3" opacity="0">*</text>
  <text class="reset0 p1payp2c0" x="45%" y="230" fill="#008eb3" opacity="1">4</text>
  <text  class="reset0 p2pay0 p2payp1d0"  x="55%" y="230" fill="#f4656d" opacity="1">0</text>
  <text class="star0 p1starp2d0" x="70%" y="230" fill="#008eb3" opacity="0">*</text>  
  <text class="reset0 p1payp2d0 p1pay0" x="75%" y="230" fill="#008eb3" opacity="1">1</text>
  <text class="reset0 p2pay0 p2payp1d0" x="85%" y="230" fill="#f4656d" opacity="1">1</text>
  <text class="star0 p2starp1d0"  x="90%" y="230" fill="#f4656d" opacity="0">*</text>
</svg>

<h1> Exercise section 0 </h1>
<%= render 'layouts/ndg' %>
<p> Can you identify Nash Equilibrium of this game? Can you do it steps by steps like in the example of the Prisoner's Dilemma? Can you think about efficiency and best responses to each contingency along the way? </p>
<p> > <span class="ans0">  </span></p>
<p><button type="button" onclick="colorne()">Answer</button></p>

app/views/static_pages/intro.html.erb
<% provide(:image, "bear.jpg") %>
<% provide(:author, "r.omas") %>

<div>
  <header>0. Introduction</header>
  <p><i> Abstract: I simulate populations of agents playing games for fitness and the population evolves under an evolutionary algorithm. The Racket code is on my Github page, further information is on the Gitlab page of this project. The general sentiment is that I put the project in the freest form possible in accordance with local regulation. In the best case, you would get it in public domain under CC0.</i></p>  
  <h1> Plain section 0</h1>
  <p> First of all, a player is a distinct set of interest. </p>
  <p> Each player has a strategy set from which they can choose from. Their strategies would be combined into different possible outcomes in a matrix with corresponding payoffs. </p>
  <p> For example, following is the payoff matrix of a very popular game: the Prisoner's Dilemma. In this game, there are 2 players and each has 2 possible strategies. Therefore there can be 4 possible outcomes. We would proceed to reason about this situation in the next chapter.
  </p>
</div>
<%= render 'layouts/pd' %>

app/views/static_pages/payoff.html.erb
<% provide(:image, "wolf.jpg") %>
<% provide(:author, "r.omas") %>


	    <header>V. Payoff Calculation </header>
	    <i> I would explain some theoretical stuff in this chapter. It is merely to describe how things are done in the field. I personally believe that the interpretations I am going to make next are very brave and a bit too far from reality. Anyway. </i>
	    <h1> Plain section 0 </h1>
	    <p> Think about the situation when we match two agents together for a game. The game can be one shot or it can be repeated for a number of rounds. If it is repeated for a number of rounds, the result is a payoff sequence for each agent. For example, the payoff sequence can be <code> 3 3 3 3 3 3...</code>How do we combine this sequence into a single number as the final payoff for the game? </p>
	    <p> Think about what the bank does. When you have a flow of cash over a period of time, they usually calculate the present value of that cash flow using some discount factor. We can think of the payoff sequence we get as a future cash flow and use a discount factor to calculate the present value of that flow. </p>

	    <p> To remind you a little bit about the ruthlessness of the financial market, here is how discount factor &delta; can be used on our payoff sequence: </p>
	    <pre class="game3">
<code> Round            0    1    2    3    4    5 ... </code>
<code> Payoff           3    3    3    3    3    3 ... </code>
<code> Discount factor  &delta;<sup>0</sup>   &delta;<sup>1</sup> </code>   &delta;<sup>2</sup>   &delta;<sup>3</sup>   &delta;<sup>4</sup>   &delta;<sup>5</sup>...</code>

<code> Present value = 3 + 3*&delta; + 3*&delta;<sup>2</sup> + ...</code>
	    </pre>
	    
	    <p> Now with the restriction that the discount factor &delta; can go from 0 to 1, we have the following cases: </p>
	    <ul>
		<li> In the case &delta; = 0; PV = 3 because all the payoffs that come after today are discounted to zero flat.  </li>
		<li> In the case &delta; = 1; PV = 3 + 3 + 3 ... which means that we simply sum up the payoff sequence. Because we regard the value of &euro;1 we get far in the future exactly the same as &euro;1 we get to hold today in our hand.</li>
		<li> In the case 0 < &delta; << 1 (which means that &delta; is small), as we go further into the payoff sequence, the present value of the payoffs would quickly drop. This is the case in which we are a bit myopic. Whoever calculate cash flows this way is someone who is very impatient. She like the money she can get today, and maybe tomorrow, but promises about stuff coming after tomorrow are considered noise to her.</li>
		<li> In the case &delta; is close to 1, as you can guess, the situation resembles someone who is highly patient. Payoff in the future is discounted a little but still bear value to her. To this person, even years from now, it is something still worth waiting for.</li>
	    </ul>

app/views/static_pages/repeated.html.erb
<% provide(:image, "damascus.jpg") %>
<% provide(:author, "c.hi") %>

<div>
  <header>II. The Repeated Game</header>
  <h1> Plain section 0 </h1>
  <p> As you see in the previous section, if the game is played for just one time between two players, the result is for both players to inevitably defect. Let's consider another variance of this game in which the game is played for more than one rounds between two players. Which means that it is played repeatedly.   </p>
  <p> Here is the payoff matrix of the game. </p>
</div>

<%= render 'layouts/pd' %>
	
<p>Let's say we play the game for 10 rounds between two players. The game can unfold as follows (there are other possible outcomes, but this one can be):</p>
<pre class="game">

  <code class="game1">&#9822; : C C D D C C D D C C</code> 
  <code class="game2">&#9820; : D D D C C C D D D D</code>

  This can be translated into the following payoff sequences for both of them:

  <code class="game1">&#9822; : 0 0 1 4 3 3 1 1 0 0</code> 
  <code class="game2">&#9820; : 4 4 1 0 3 3 1 1 4 4</code>

  
</pre>

<p> We can see that in each round there are 2 possible actions hence a game with 10 rounds would have a strategy set containing of 2<sup>10</sup> possible strategies. If we draw the payoff matrix of that game, it would be a very big one and it becomes incredibly difficult to calculate a solution analytically. Worse, if we suppose to play the game infinitely, then the number of strategy becomes 2<sup>&infin;</sup>. The repitition of this game, therefore, motivates a general problem of searching for optima in vast space. Exactly why the neurons fire up about computer simulation. Yay!</p> 
<h1> Exercise section 0 </h1>
<%= render 'layouts/ndg' %>

<p> Can you think about the repeated version of this game?</p>


	  <p> > <span class="ans">  </span></p>

	<p>	<button type="button" onclick="answer()">Answer</button></p>

app/views/static_pages/run.html.erb
<% provide(:image, "garden2.jpg") %>
<% provide(:author, "s.im") %>


<header> Run </header>

Hello, I have been working on the simulation. And at this point I am able to deploy something that can run for you. Here:

<a href="https://still-caverns-39622.herokuapp.com/"> a draft heroku app </a>

If you run it for several time, you would see that the population average goes up and down in cycle. When it is down, the whole population is defecting: everybody defects everybody. When it is up, it means that everybody is cooperating.

I am still thinking of making something you can adjust, looking at the population to see what kind of strategies is in there..

app/views/static_pages/sandbox.html.erb
<h1>StaticPages#sandbox</h1>
<p>Find me in app/views/static_pages/sandbox.html.erb</p>

<%= render 'layouts/pd' %>